"""Every address that appears in a generated fixture comes from here.

The module is *incapable* of emitting a real-looking address: the domain list
is a literal tuple of RFC 2606 reserved names, and nothing here composes a
domain from an argument, an environment variable, or the host. There is no code
path that reaches a real domain, which is the property
`tests/test_fixture_addresses.py` asserts — against generated bytes, not against
call sites, because a call site can be bypassed and bytes cannot.

This matters more than it looks. `email.utils.make_msgid()` is the obvious way
to build a Message-ID and it calls `socket.getfqdn()`, which would stamp the
build machine's hostname into every fixture — a real infrastructure identifier
in a public repository, and non-deterministic besides. Hence `message_id()`.
"""

from __future__ import annotations

import random

# RFC 2606: example.{com,net,org} at the second level, and the .test,
# .example, .invalid and .localhost TLDs. Nothing else is permitted, and the
# test asserts every generated address ends with one of these.
RESERVED_DOMAINS: tuple[str, ...] = (
    "example.com",
    "example.net",
    "example.org",
    "mail.example",
    "lists.example.test",
    "corp.example.invalid",
    "archive.test",
    "legacy.invalid",
    "newsletter.example.com",
)

_LOCAL_PARTS: tuple[str, ...] = (
    "alice",
    "bob",
    "carol",
    "dave",
    "erin",
    "frank",
    "grace",
    "heidi",
    "ivan",
    "judy",
    "mallory",
    "oscar",
    "peggy",
    "trent",
    "walter",
    "no-reply",
    "notifications",
    "support",
    "billing",
    "list-bounces",
)

_DISPLAY_NAMES: tuple[str, ...] = (
    "Alice Example",
    "Bob Example",
    "Carol Example",
    "Dave Example",
    "Erin Example",
    "Grace Example",
    "Heidi Example",
    # Non-ASCII display names are ordinary in real mail and force RFC 2047
    # encoding on the way out; they are not a pathology.
    "Zoë Example",
    "Renée Example",
    "李雷",
    "Björn Example",
)


def pick_address(rng: random.Random) -> str:
    """A bare addr-spec, always inside a reserved domain."""
    local = rng.choice(_LOCAL_PARTS)
    domain = rng.choice(RESERVED_DOMAINS)
    return f"{local}@{domain}"


def pick_display_address(rng: random.Random) -> str:
    """A `Display Name <addr>` pair, always inside a reserved domain."""
    return f"{rng.choice(_DISPLAY_NAMES)} <{pick_address(rng)}>"


def message_id(rng: random.Random, index: int) -> str:
    """Deterministic Message-ID.

    Never `email.utils.make_msgid` — see the module docstring for why.
    """
    host = rng.choice(RESERVED_DOMAINS)
    return f"<fixture-{index:08d}.{rng.getrandbits(32):08x}@{host}>"


def is_reserved(address: str) -> bool:
    """True if `address` sits in an RFC 2606 domain. Used by the guard test."""
    _, _, domain = address.rpartition("@")
    domain = domain.rstrip(">").lower()
    return any(
        domain == d or domain.endswith("." + d) for d in RESERVED_DOMAINS
    ) or domain.endswith((".test", ".example", ".invalid", ".localhost"))
